### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by jtraglia**
This PR fixes a bunch of typos throughout the project.

### CODE REVIEW

**Review by kdeme — COMMENTED** [review]
Great, thanks for going through all that :)

lgtm, can you just fix those missing camelCases?

**Comment by jtraglia** [comment]
Ah yes, good spot. That was a bad find/replace on my part. Fixed!

**Comment by kdeme** [comment]
@jtraglia Sorry, but it seems you missed adjusting the `currentslowStartThreshold` ones?

**Comment by jtraglia** [comment]
Yeah I missed that somehow. Sorry about that. It's fixed.

**Pull request merged**
