### PR TITLE
*.nimble: remove imports

### PR DESCRIPTION
**Pull request by stefantalpalaru**
- also speed up the tests with release builds

### CODE REVIEW

**Comment by arnetheduck** [comment]
we tend to have an `all_tests.nim` that collects all tests in a single file, like here: https://github.com/status-im/nim-beacon-chain/blob/master/tests/all_tests.nim

this is nice because it allows to run individual tests from command line but requires only a single compile for the big test.. maybe something similar here would be good

**Comment by stefantalpalaru** [comment]
This is a repo obtained from merging 5 different repos with separate test suites. There was a requirement to still be able to run those test suites individually. If we move to an "all_tests.nim", we also need 5 more "all_foo_tests.nim" besides it.

Some tests use "\*.json" files and I think the path to them is relative to the current directory- i.e.: the binary needs to be run in "tests/rlp" or "tests/trie".

**Comment by arnetheduck** [comment]
> If we move to an "all_tests.nim", we also need 5 more "all_foo_tests.nim" beside it.

that's probably not a bad way to organize things

**Comment by arnetheduck** [comment]
in particular, it seems better to keep it in nim files than in nimble

**Pull request merged**
