### PR TITLE
fix nimbus/premix appveyor build

### PR DESCRIPTION
**Pull request by jangko**
this PR fix recent nimbus appveyor failed build

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
If this fix works, Chronicles is off the hook here: https://github.com/status-im/nim-chronicles/issues/50

**Comment by jangko** [comment]
it works on my windows machine.
technically, it is not gcsafe, due to chronicles `debug` presence.
but we can pretend it is gcsafe, at least for release build

**Comment by stefantalpalaru** [comment]
If we pretend now, the root cause will come back to bite us later.

**Comment by jangko** [comment]
I see some of the other callbacks also marked `{.gcsafe.}` (not only me have the same idea here)
it will bite us back at many places. unless we can make chronicles evade nim compiler sensor detection like `debugEcho`.

**Pull request merged**
