### PR TITLE
Add a new asyncDiscard replacement that traces recoverable errors and aborts on defects

### PR DESCRIPTION
**Pull request by zah**

### CODE REVIEW

**Comment by yglukhov** [comment]
How about (a) adding this to chronos, and (b) provide only an explicit way of specifying error handler in case of CatchableError, eg.
```
myAsyncProc().asyncCheck do(e: CatchableError):
  # my handler
```

**Comment by zah** [comment]
We can do this, but let's revisit it after the testnet launch.

**Comment by yglukhov** [comment]
> We can do this, but let's revisit it after the testnet launch.

Why not now? It's like a 5 minutes change.

**Comment by zah** [comment]
@cheatfate can add the helper in Chronos when he has the time, but even with it, we'll could still use the chronicles-enable wrapper in nim-eth, anyway.

**Pull request merged**
