### PR TITLE
don't swallow random exceptions

### PR DESCRIPTION
**Pull request by arnetheduck**

### CODE REVIEW

**Comment by tersec** [comment]
I'm in favor of this PR.

**Comment by arnetheduck** [comment]
this is a follow-up on https://github.com/status-im/nim-eth-p2p/pull/56

funny enough, looks like tests fail because of a previously swallowed exception ;)

**Comment by arnetheduck** [comment]
randomly, on some platforms, at that!

**Comment by yglukhov** [comment]
I've seen this test failing before. cc @kdeme

**Comment by kdeme** [comment]
@yglukhov I thought the failure you saw before was with the mocked version of the test.

I think this failure at test_shh_connect is related to this PR. That is, the issue is probably always/often there, but the error only shows up now. I will investigate.

**Comment by yglukhov** [comment]
I could be wrong, but here's a recent build from nim-eth-p2p, master branch. The failure is not exactly the same, but feels somewhat similar to me. https://travis-ci.org/status-im/nim-eth-p2p/jobs/485331507

**Pull request merged**
